### ISSUE TITLE
Error while storing card

### ISSUE THREAD

**Issue by generosocarbone** [developermypos/myPOS-Mobile-Checkout-SDK-Android#5]
I can't **store** a card while the app is NOT in sandbox

> W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
> W/System.err:     at com.mypos.mobilepaymentssdk.CryptoHandler.verifySignature(CryptoHandler.java:92)
> W/System.err:     at com.mypos.mobilepaymentssdk.IPCHttpCommunication$1.run(IPCHttpCommunication.java:76)
> W/System.err:     at java.lang.Thread.run(Thread.java:919)

I configured the app using the webpack string taken from the dashboard and I'm using the following sdk
**implementation 'com.mypos:mobilepaymentssdk:1.0.7'**

**Comment by generosocarbone** [comment]
Even if use this sdk version **implementation 'com.mypos:checkoutsdk:1.0.6'** I get the same error in the same line

> W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
> W/System.err:     at com.mypos.mobilepaymentssdk.CryptoHandler.verifySignature(CryptoHandler.java:92)
> W/System.err:     at com.mypos.mobilepaymentssdk.IPCHttpCommunication$1.run(IPCHttpCommunication.java:76)
> W/System.err:     at java.lang.Thread.run(Thread.java:919)
